CREATE TABLE IF NOT EXISTS assets(
  id SERIAL PRIMARY KEY, symbol TEXT UNIQUE NOT NULL
);
CREATE TABLE IF NOT EXISTS candles(
  asset_id INT REFERENCES assets(id),
  ts TIMESTAMPTZ NOT NULL,
  o DOUBLE PRECISION, h DOUBLE PRECISION, l DOUBLE PRECISION, c DOUBLE PRECISION, v DOUBLE PRECISION,
  PRIMARY KEY (asset_id, ts)
);
CREATE TABLE IF NOT EXISTS signals(
  id BIGSERIAL PRIMARY KEY,
  asset_id INT REFERENCES assets(id),
  ts TIMESTAMPTZ NOT NULL,
  regime TEXT NOT NULL,
  direction TEXT CHECK (direction IN ('long','flat','short')) NOT NULL,
  strength DOUBLE PRECISION,
  reason JSONB
);
CREATE TABLE IF NOT EXISTS paper_trades(
  id BIGSERIAL PRIMARY KEY,
  signal_id BIGINT REFERENCES signals(id),
  ts TIMESTAMPTZ NOT NULL,
  side TEXT CHECK (side IN ('buy','sell')),
  price DOUBLE PRECISION,
  size DOUBLE PRECISION,
  pnl DOUBLE PRECISION DEFAULT 0
);
